[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
